//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEmployeeService")]
public interface IEmployeeService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeById", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeByIdResponse")]
    string GetEmployeeById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeById", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeByIdResponse")]
    System.Threading.Tasks.Task<string> GetEmployeeByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/EnableEmployee", ReplyAction="http://tempuri.org/IEmployeeService/EnableEmployeeResponse")]
    void EnableEmployee(int id, int enable);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/EnableEmployee", ReplyAction="http://tempuri.org/IEmployeeService/EnableEmployeeResponse")]
    System.Threading.Tasks.Task EnableEmployeeAsync(int id, int enable);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEmployeeServiceChannel : IEmployeeService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<IEmployeeService>, IEmployeeService
{
    
    public EmployeeServiceClient()
    {
    }
    
    public EmployeeServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetEmployeeById(int id)
    {
        return base.Channel.GetEmployeeById(id);
    }
    
    public System.Threading.Tasks.Task<string> GetEmployeeByIdAsync(int id)
    {
        return base.Channel.GetEmployeeByIdAsync(id);
    }
    
    public void EnableEmployee(int id, int enable)
    {
        base.Channel.EnableEmployee(id, enable);
    }
    
    public System.Threading.Tasks.Task EnableEmployeeAsync(int id, int enable)
    {
        return base.Channel.EnableEmployeeAsync(id, enable);
    }
}
